#187 Add possibility to configure the standard download folder
Xceptance/neodymium-library pull request #188
Opened 2021-05-31 15:35 UTC by oomelianchuk

This PR contains changes to enable browser preferences configuration for chrome and firefox and therefore changing the default download directory for these browsers.

2021-06-03 12:47 UTC, occupant23 requested changes
Please divide the changes into two different PRs as discussed.
One only setting the downloads folder just via one configuration.
One introducing the a general approach to set preferences. (Create a separate ticket for this)

2021-06-07 14:50 UTC, oomelianchuk commented
Support of browser preferences has been removed from this PR and moved to PR #193

2023-07-28 10:41 UTC, oomelianchuk commented on src/main/java/com/xceptance/neodymium/module/statement/browser/multibrowser/BrowserRunnerHelper.java
> +                if (config.getDownloadDirectory() != null && !config.getDownloadDirectory().isEmpty())
no, used now, thanks for the hint :)

2023-07-28 10:41 UTC, oomelianchuk commented on src/main/java/com/xceptance/neodymium/module/statement/browser/multibrowser/BrowserRunnerHelper.java
> +                if (config.getDownloadDirectory() != null && !config.getDownloadDirectory().isEmpty())
no, used now, thanks for the hint :)

2023-07-28 10:41 UTC, oomelianchuk commented on src/main/java/com/xceptance/neodymium/module/statement/browser/multibrowser/BrowserRunnerHelper.java
> +    private static String popularContentTypes()
done

2023-07-28 11:04 UTC, oomelianchuk commented on src/main/java/com/xceptance/neodymium/module/statement/browser/multibrowser/configuration/BrowserConfigurationMapper.java
> -        capabilities.setCapability("name", browserProfileConfiguration.get("name"));
hm, I also don't see any reason why the line should be deleted. The change is reverted

2023-07-28 11:04 UTC, oomelianchuk commented on src/test/java/com/xceptance/neodymium/testclasses/webDriver/DownloadFilesInDifferentWays.java
> +    public void downloadOnFormSubmission()
Done

2023-07-28 11:04 UTC, oomelianchuk commented on src/test/java/com/xceptance/neodymium/testclasses/webDriver/DownloadFilesInDifferentWays.java
> +public class DownloadFilesInDifferentWays extends NeodymiumTest
JavaDoc is added

2023-07-28 11:04 UTC, oomelianchuk commented on src/test/java/com/xceptance/neodymium/tests/DownloadFilesExecutorTest.java
> +public class DownloadFilesExecutorTest extends NeodymiumTest
JavaDoc is added

2024-01-26 12:46 UTC, wurzelkuchen approved these changes
looks good, thanks

2024-01-26 12:46 UTC, merged