#162 Support Test Recording
Xceptance/neodymium-library pull request #196
Opened 2021-06-21 15:55 UTC by oomelianchuk

2024-02-23 22:17 UTC, wurzelkuchen requested changes
Part one of my review. More will follow.

2024-03-26 06:12 UTC, wurzelkuchen requested changes

2024-03-26 06:12 UTC, wurzelkuchen commented on src/test/java/com/xceptance/neodymium/tests/visual/ai/Test_Images_ESF.network
This seems out of place, video recording does not use visual compare. Check if this is used somewhere in the code, if not, remove it from this branch.

2024-03-26 10:28 UTC, wurzelkuchen commented on src/main/java/com/xceptance/neodymium/recording/config/GifRecordingConfigurations.java
> +  "${recording.temporaryConfigFile}", "system:env", "system:properties", "file:config/dev-gif-recording.properties", "file:config/gif-recording.properties"
We should add neodymium.properties and dev-neodymium properties here, to get a better coverage, with less confusion, which property needs to be where

2024-03-27 09:21 UTC, kqmpetenz commented on src/main/java/com/xceptance/neodymium/recording/config/RecordingConfigurations.java
> +public interface RecordingConfigurations extends Mutable
Do you want one RecordingConfiguration Class combining the two (video and gif) or do you want a specific configuration class for each format?

2024-04-10 13:23 UTC, wurzelkuchen approved these changes

2024-04-10 13:23 UTC, merged