Dependency update snakeyaml
Xceptance/neodymium-library pull request #223
Opened 2022-12-06 10:41 UTC by RobertAvemarg

updated snakeyaml dependency and we changed the website from xceptance to posters.xceptance.io and adjusted the slider value in SelenideAddonsTest to make the tests pass again

2022-12-06 11:43 UTC, oomelianchuk approved these changes
The changes seem good to me. The Jenkins run for this branch was also successful. Thanks @RobertAvemarg for the great work!

2022-12-13 07:09 UTC, occupant23 requested changes

2022-12-13 07:09 UTC, occupant23 commented on src/test/java/com/xceptance/neodymium/util/SelenideAddonsTest.java
> +        openPostersStartPage();
Use 'mozzarella' as search term and perform similar like in the old example.

2022-12-13 07:09 UTC, occupant23 commented on src/test/java/com/xceptance/neodymium/util/SelenideAddonsTest.java
> +        $("#searchForm input").val("bear").submit();
Use 'mozzarella' as search term and perform similar like in the old example. 
(Use ^ and $ in the regex)

2022-12-13 07:09 UTC, occupant23 commented on src/test/java/com/xceptance/neodymium/util/SelenideAddonsTest.java
> +        $("#searchForm input").val("bear").submit();
Use 'mozzarella' as search term and perform similar like in the old example.

2022-12-13 07:09 UTC, occupant23 commented on src/test/java/com/xceptance/neodymium/util/SelenideAddonsTest.java
> +            $("#searchForm input").should(SelenideAddons.matchValue("\\d+"));
this validation should check the content area e.g. '.header-container #titleSearchText.

2022-12-13 07:10 UTC, occupant23 commented
@RobertAvemarg I found some small things please adjust.

2022-12-13 11:07 UTC, occupant23 approved these changes

2022-12-13 11:08 UTC, occupant23 commented
@oomelianchuk Please perform the merge and release it together with @RobertAvemarg

2022-12-13 13:22 UTC, merged